root_dir: 'D:/lycaoduong/workspace/datasets/others/cancer/dataset'
train_dir : 'D:/lycaoduong/workspace/datasets/others/cancer/dataset/train.csv'
val_dir : 'D:/lycaoduong/workspace/datasets/others/cancer/dataset/val.csv'
test_dir : 'D:/lycaoduong/workspace/datasets/others/cancer/dataset/test.csv'
cls_name: ["breast_cancer", "breast_normal", "thyroid_cancer", "thyroid_normal", "lung_cancer", "lung_normal"]
num_cls: 6